// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srtjpzpkykrbbtfaynwl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNydGpwenBreWtyYmJ0ZmF5bndsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTA2NDgsImV4cCI6MjA2MDkyNjY0OH0.CaO1HZftESE2ZAxkDMJum1fJvukSGNLX9vCHl8bVrQM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);